# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.changelog_schema import ChangelogSchema

class TestChangelogSchema(unittest.TestCase):
    """ChangelogSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangelogSchema:
        """Test ChangelogSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangelogSchema`
        """
        model = ChangelogSchema()
        if include_optional:
            return ChangelogSchema(
                version = '2.49.0',
                data = '29-11-2022',
                highlights = [
                    thingiverse.models.changelog_schema_highlights_inner.changelog_schema_highlights_inner(
                        title = '', 
                        content = '', )
                    ],
                features = [
                    ''
                    ],
                bugfixes = [
                    ''
                    ]
            )
        else:
            return ChangelogSchema(
        )
        """

    def testChangelogSchema(self):
        """Test ChangelogSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
