# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.subscriptions0_analytics_get200_response import Subscriptions0AnalyticsGet200Response

class TestSubscriptions0AnalyticsGet200Response(unittest.TestCase):
    """Subscriptions0AnalyticsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subscriptions0AnalyticsGet200Response:
        """Test Subscriptions0AnalyticsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subscriptions0AnalyticsGet200Response`
        """
        model = Subscriptions0AnalyticsGet200Response()
        if include_optional:
            return Subscriptions0AnalyticsGet200Response(
                stats = thingiverse.models._subscriptions_0_analytics_get_200_response_stats._subscriptions_0_analytics_get_200_response_stats(
                    views = '', 
                    downloads = '', 
                    likes = '', 
                    collects = '', 
                    makes = '', ),
                thing_count = 56
            )
        else:
            return Subscriptions0AnalyticsGet200Response(
        )
        """

    def testSubscriptions0AnalyticsGet200Response(self):
        """Test Subscriptions0AnalyticsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
