# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.thing_zip_data_files_inner import ThingZipDataFilesInner

class TestThingZipDataFilesInner(unittest.TestCase):
    """ThingZipDataFilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThingZipDataFilesInner:
        """Test ThingZipDataFilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThingZipDataFilesInner`
        """
        model = ThingZipDataFilesInner()
        if include_optional:
            return ThingZipDataFilesInner(
                name = '3DBenchy_Broschure_3DBenchy.com.pdf',
                url = 'https://cdn.thingiverse.com/assets/a7/2c/bd/ba/ea/3DBenchy_Broschure_3DBenchy.com.pdf'
            )
        else:
            return ThingZipDataFilesInner(
        )
        """

    def testThingZipDataFilesInner(self):
        """Test ThingZipDataFilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
