# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.collections_collection_id_thing_thing_id_post_request import CollectionsCollectionIdThingThingIdPostRequest

class TestCollectionsCollectionIdThingThingIdPostRequest(unittest.TestCase):
    """CollectionsCollectionIdThingThingIdPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionsCollectionIdThingThingIdPostRequest:
        """Test CollectionsCollectionIdThingThingIdPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionsCollectionIdThingThingIdPostRequest`
        """
        model = CollectionsCollectionIdThingThingIdPostRequest()
        if include_optional:
            return CollectionsCollectionIdThingThingIdPostRequest(
                description = None
            )
        else:
            return CollectionsCollectionIdThingThingIdPostRequest(
        )
        """

    def testCollectionsCollectionIdThingThingIdPostRequest(self):
        """Test CollectionsCollectionIdThingThingIdPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
