# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.api.category_api import CategoryApi


class TestCategoryApi(unittest.TestCase):
    """CategoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoryApi()

    def tearDown(self) -> None:
        pass

    def test_categories_get(self) -> None:
        """Test case for categories_get

        List of root categories. Does not list any sub categories.
        """
        pass

    def test_categories_slug_get(self) -> None:
        """Test case for categories_slug_get

        Get category by slug
        """
        pass

    def test_categories_slug_things_get(self) -> None:
        """Test case for categories_slug_things_get

        Get list of things of the corresponding category by slug
        """
        pass

    def test_categoriesreturncomplete_get(self) -> None:
        """Test case for categoriesreturncomplete_get

        List of root categories and their nested children.
        """
        pass


if __name__ == '__main__':
    unittest.main()
