# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.api.printer_api import PrinterApi


class TestPrinterApi(unittest.TestCase):
    """PrinterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PrinterApi()

    def tearDown(self) -> None:
        pass

    def test_printers0_brands_get(self) -> None:
        """Test case for printers0_brands_get

        Get a list of all known printer brands
        """
        pass

    def test_printers0_models_get(self) -> None:
        """Test case for printers0_models_get

        Get a list of known printers
        """
        pass


if __name__ == '__main__':
    unittest.main()
