# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.api.tag_api import TagApi


class TestTagApi(unittest.TestCase):
    """TagApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagApi()

    def tearDown(self) -> None:
        pass

    def test_tags0_popular_get(self) -> None:
        """Test case for tags0_popular_get

        Get the list of random popular tags.
        """
        pass

    def test_tags_get(self) -> None:
        """Test case for tags_get

        Get the list of tags.
        """
        pass

    def test_tags_tag_get(self) -> None:
        """Test case for tags_tag_get

        Return a representation of the given tag
        """
        pass

    def test_tags_tag_search_tags_get(self) -> None:
        """Test case for tags_tag_search_tags_get

        Search tags by tag name.
        """
        pass

    def test_tags_tag_things_get(self) -> None:
        """Test case for tags_tag_things_get

        Get the latest things with the specified tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
