# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.api.verified_api import VerifiedApi


class TestVerifiedApi(unittest.TestCase):
    """VerifiedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerifiedApi()

    def tearDown(self) -> None:
        pass

    def test_verified_get(self) -> None:
        """Test case for verified_get

        Get the latest things verified
        """
        pass


if __name__ == '__main__':
    unittest.main()
