# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.copies_copy_id_comments_post_request import CopiesCopyIdCommentsPostRequest

class TestCopiesCopyIdCommentsPostRequest(unittest.TestCase):
    """CopiesCopyIdCommentsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CopiesCopyIdCommentsPostRequest:
        """Test CopiesCopyIdCommentsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CopiesCopyIdCommentsPostRequest`
        """
        model = CopiesCopyIdCommentsPostRequest()
        if include_optional:
            return CopiesCopyIdCommentsPostRequest(
                body = 'the message to post',
                recaptcha_token = ''
            )
        else:
            return CopiesCopyIdCommentsPostRequest(
                body = 'the message to post',
                recaptcha_token = '',
        )
        """

    def testCopiesCopyIdCommentsPostRequest(self):
        """Test CopiesCopyIdCommentsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
