# coding: utf-8

"""
    API documentation

    API for thingiverse.com

    The version of the OpenAPI document: 0.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from thingiverse.models.email_schema import EmailSchema

class TestEmailSchema(unittest.TestCase):
    """EmailSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailSchema:
        """Test EmailSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailSchema`
        """
        model = EmailSchema()
        if include_optional:
            return EmailSchema(
                body = thingiverse.models.email_body.Email_body(
                    user_id = 56, 
                    email_sent = '', )
            )
        else:
            return EmailSchema(
        )
        """

    def testEmailSchema(self):
        """Test EmailSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
